main:
    random_seed: 'nips2020'
    saved_dir: '/home/tony/SceneFlow/models/flyingthings/pwcnet_rgbd/train'

dataset:
    name: 'PWCRGBDDataset'
    kwargs:
        data_dir: '/home/tony/datasets/flyingthings3d_preprocessed'
        data_split_csv: '/home/tony/SceneFlow/flyingthings3d_split_03.csv'
        train_preprocessings:
            - name: 'RandomCrop'
              kwargs:
                  size: [480, 480]
        valid_preprocessings:
        augments:
        transforms:
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 12
        valid_batch_size: 2
        shuffle: true
        num_workers: 4

net:
    name: 'PWCRGBDNet'
    kwargs:
        device: 'cuda:0'
        lv_chs: [3, 16, 32, 64, 96, 128, 192]
        search_range: 4
        batch_norm: True
        corr_activation: True
        residual: True
        output_level: 4
        depth_factor: 2

losses:
    - name: 'FlowL2Error'
      weight: 1.0
    # - name: 'FlowL2Error'
    #   weight: 0.5
    # - name: 'DispL2Error'
    #   weight: 0.25
    # - name: 'DispNextL2Error'
    #   weight: 0.25

metrics:
    # - name: 'FlowL2Error'
    # - name: 'DispL2Error'
    # - name: 'DispNextL2Error'
    - name: 'FlowL2Error'
    - name: 'F1Score'
      kwargs:
        threshold: 0.05

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: 'StepLR'
    kwargs:
        step_size: 100
        gamma: 0.1

logger:
    name: 'PWCSceneLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 25
        early_stop: 0

trainer:
    name: 'PWCRGBDTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 300
