main:
    random_seed: 'nips2020'
    saved_dir: '/home/tungi893610/SceneFlow/models/flyingthings/pwcnet_disparity_crop/train'

dataset:
    name: 'PWCDisparityDataset'
    kwargs:
        data_dir: '/work/tungi893610//flyingthings3d_preprocessed'
        data_split_csv: '/home/tungi893610/SceneFlow/flyingthings3d_split.csv'
        train_preprocessings:
            - name: 'RandomCrop'
              kwargs:
                  size: [512, 512]
        valid_preprocessings:
        augments:
        transforms:
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 32
        valid_batch_size: 4
        shuffle: true
        num_workers: 4

net:
    name: 'PWCDNet'
    kwargs:
        device: 'cuda:1'
        lv_chs: [3, 16, 32, 64, 96, 128, 192]
        search_range: 4
        batch_norm: True
        corr_activation: True
        residual: True
        output_level: 4

losses:
    - name: 'MyL2Loss'
      weight: 1.0

metrics:
    - name: 'EPE'
    # - name: 'Accuracy'
    #   kwargs:
    #     threshold: 0.1

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: 'StepLR'
    kwargs:
        step_size: 100
        gamma: 0.1

logger:
    name: 'PWCDisparityLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 25
        early_stop: 0

trainer:
    name: 'PWCDisparityTrainer'
    kwargs:
        device: 'cuda:1'
        num_epochs: 300
